"""Celery standalone configuration."""
broker_url = "redis://:cerberus_redis@localhost:6379/1"
result_backend = "redis://:cerberus_redis@localhost:6379/2"
task_serializer = "json"
accept_content = ["json"]
result_serializer = "json"
timezone = "UTC"
enable_utc = True
task_track_started = True
task_time_limit = 3600
task_soft_time_limit = 3000
worker_prefetch_multiplier = 1
worker_max_tasks_per_child = 100
