/**
 * Reports Page — Uses useReports hook for report management.
 */

import { useParams } from "react-router-dom";
import DashboardLayout from "../components/layout/DashboardLayout";
import { useReports } from "../hooks/useReports";
import { useQuery } from "@tanstack/react-query";
import { engagementService } from "../services/engagement";

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

interface EngagementListItem {
  id: string;
  project_name: string;
  created_at: string;
  overall_security_score?: number;
  status: string;
}

interface EngagementListResponse {
  items: EngagementListItem[];
  total: number;
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export default function ReportsPage() {
  const { engagementId } = useParams<{ engagementId: string }>();
  const { generate } = useReports(engagementId || "");

  const { data: engagements, isLoading } = useQuery<EngagementListResponse>({
    queryKey: ["all-engagements-for-reports"],
    queryFn: () =>
      engagementService
        .list({ page: 1, page_size: 50 })
        .then((res: { data: EngagementListResponse }) => res.data),
  });

  return (
    <DashboardLayout activeItem="reports">
      <div className="space-y-6">
        <h1 className="text-3xl font-bold text-white">Reports Center</h1>
        <p className="text-gray-400">
          Access every penetration testing report generated by the platform.
          Preview reports, download PDF copies, and track your security posture over time.
        </p>

        {isLoading ? (
          <div className="cyber-card text-center text-gray-400 py-12">Loading reports...</div>
        ) : (
          <div className="cyber-card overflow-hidden">
            <table className="w-full text-left">
              <thead>
                <tr className="border-b border-cerberus-gray-700">
                  <th className="p-4 text-sm text-gray-400 font-medium">Assessment</th>
                  <th className="p-4 text-sm text-gray-400 font-medium">Date</th>
                  <th className="p-4 text-sm text-gray-400 font-medium">Score</th>
                  <th className="p-4 text-sm text-gray-400 font-medium">Status</th>
                  <th className="p-4 text-sm text-gray-400 font-medium">Actions</th>
                </tr>
              </thead>
              <tbody>
                {engagements?.items?.length ? (
                  engagements.items.map((eng) => (
                    <tr key={eng.id} className="border-b border-cerberus-gray-700/50">
                      <td className="p-4 text-sm text-white">{eng.project_name}</td>
                      <td className="p-4 text-sm text-gray-400">
                        {new Date(eng.created_at).toLocaleDateString()}
                      </td>
                      <td className="p-4 text-sm text-cerberus-blue font-bold">
                        {eng.overall_security_score ?? "—"}/100
                      </td>
                      <td className="p-4 text-sm">
                        <span
                          className={`px-2 py-0.5 text-xs rounded-full ${
                            eng.status === "completed"
                              ? "bg-green-500/20 text-green-400"
                              : "bg-yellow-500/20 text-yellow-400"
                          }`}
                        >
                          {eng.status}
                        </span>
                      </td>
                      <td className="p-4 text-sm">
                        {eng.status === "completed" && (
                          <button
                            onClick={() => generate.mutate()}
                            className="text-cerberus-blue hover:underline text-xs"
                          >
                            Download PDF
                          </button>
                        )}
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan={5} className="p-8 text-center text-gray-500">
                      <span className="text-3xl block mb-2">📄</span>
                      No reports generated yet. Complete an assessment to generate your first report.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
